### ISSUE TITLE
TridesclousSortingExtractor requires write permission

### ISSUE THREAD

**Issue by JuliaSprenger** [SpikeInterface/spikeinterface#466] opened 2022-01-18 09:45 UTC
When reading a tridesclous sorting of files with read-only permission the TridesclousSortingExtractor fails due to a PermissionError.
```
    sorting = TridesclousSortingExtractor(folder_path=output_folder)
../../extractors/tridesclousextractors.py:22: in __init__
    dataio = tdc.DataIO(str(tdc_folder))
../../../../../site-packages/tridesclous/dataio.py:127: in __init__
    self._open_processed_data()
../../../../../site-packages/tridesclous/dataio.py:495: in _open_processed_data
    self.arrays[chan_grp][i].load_if_exists(name)
../../../../../site-packages/tridesclous/iotools.py:294: in load_if_exists
    arr = np.memmap(self._fname(name), dtype=dtype, mode='r+')
PermissionError: [Errno 13] Permission denied: 'sorters/tests/sorting_tdc_docker/channel_group_0/segment_0/processed_signals.raw'
```

I don't think the writing permission should be required for extracting the sorting information. Maybe it would be good to introduce a reading mode flag here?

**Comment by JuliaSprenger** [comment] 2022-01-18 20:49
It is the output of a sorting run in a docker container. But I could also imagine sorting results being read-only for some users on purpose.

**Comment by alejoe91** [comment] 2022-04-01 10:00
Duplicate of https://github.com/SpikeInterface/spikeinterface/issues/474

**Closed by alejoe91** 2022-04-01 10:00 UTC
Labels: container
