### ISSUE TITLE
Waveforms extractor and memory usage

### ISSUE THREAD

**Issue by yger** [SpikeInterface/spikeinterface#442] opened 2022-01-11 12:49 UTC
It would be nice if the WaveformExtractor could have an option not to cache all the waveforms in memory. Because for large recordings, a call to waveform.get_all_templates() for example is consuming almost all the memory, since waveforms are loaded, but kept by the objects internally. Why such a behavior?

**Comment by samuelgarcia** [comment] 2022-01-11 12:58
It is on my todo list.

**Comment by alejoe91** [comment] 2022-01-13 11:47
duplicate of https://github.com/SpikeInterface/spikeinterface/issues/331

**Comment by alejoe91** [comment] 2022-01-14 11:40
https://github.com/SpikeInterface/spikeinterface/pull/451

**Closed by alejoe91** 2022-01-14 11:40 UTC
Labels: bug, duplicate
