### ISSUE TITLE
Error reading OpenEphys legacy format with neo

### ISSUE THREAD

**Issue by ToGauvrit** [SpikeInterface/spikeinterface#329] opened 2021-10-25 09:10 UTC
Hi @samuelgarcia! 
Here is the issue for the reading of OpenEphys legacy format I told you in Lyon school. The problem come from neo library, the reading is not working if we have  CH and ADC channels, but working if we have only one type of channel. The error I got: 

```

  File "/datas/Théo/Spikesorting/Test1Spikeinterface.py", line 24, in <module>
    recording = se.read_openephys(folder_path)
  File "/datas/Théo/Spikesorting/venv/python/lib/python3.8/site-packages/spikeinterface/extractors/neoextractors/openephys.py", line 108, in read_openephys
    recording = OpenEphysLegacyRecordingExtractor(folder_path, **kwargs)
  File "/datas/Théo/Spikesorting/venv/python/lib/python3.8/site-packages/spikeinterface/extractors/neoextractors/openephys.py", line 38, in __init__
    NeoBaseRecordingExtractor.__init__(self, stream_id=stream_id, **neo_kwargs)
  File "/datas/Théo/Spikesorting/venv/python/lib/python3.8/site-packages/spikeinterface/extractors/neoextractors/neobaseextractor.py", line 26, in __init__
    _NeoBaseExtractor.__init__(self, **neo_kwargs)
  File "/datas/Théo/Spikesorting/venv/python/lib/python3.8/site-packages/spikeinterface/extractors/neoextractors/neobaseextractor.py", line 16, in __init__
    self.neo_reader.parse_header()
  File "/datas/Théo/Spikesorting/venv/python/lib/python3.8/site-packages/neo/rawio/baserawio.py", line 185, in parse_header
    self._parse_header()
  File "/datas/Théo/Spikesorting/venv/python/lib/python3.8/site-packages/neo/rawio/openephysrawio.py", line 176, in _parse_header
    stream_ids = stream_ids[order]
IndexError: index 32 is out of bounds for axis 0 with size 2
```

It seems that the CH and ADC channels name splitting is wrong.
Thank you for help ;)

**Comment by cxrodgers** [comment] 2022-02-08 22:43
Hi Sam, it's been a while! Hope you are well. I came across this page because I am having the same error. Also using an OpenEphys file with two types of data streams, 64 neural channels and 6 accelerometer channels.

```
In [10]: spikeinterface.extractors.read_openephys(folder_path)
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-10-85b1e1aaa4ce> in <module>
----> 1 spikeinterface.extractors.read_openephys(folder_path)

~/miniconda3/envs/py3/lib/python3.9/site-packages/spikeinterface/extractors/neoextractors/openephys.py in read_openephys(folder_path, **kwargs)
    106     if np.any([f.endswith('continuous') for f in files]):
    107         #  format = 'legacy'
--> 108         recording = OpenEphysLegacyRecordingExtractor(folder_path, **kwargs)
    109     else:
    110         # format = 'binary'

~/miniconda3/envs/py3/lib/python3.9/site-packages/spikeinterface/extractors/neoextractors/openephys.py in __init__(self, folder_path, stream_id)
     36     def __init__(self, folder_path, stream_id=None):
     37         neo_kwargs = {'dirname': folder_path}
---> 38         NeoBaseRecordingExtractor.__init__(self, stream_id=stream_id, **neo_kwargs)
     39 
     40         self._kwargs = dict(folder_path=str(folder_path), stream_id=stream_id)

~/miniconda3/envs/py3/lib/python3.9/site-packages/spikeinterface/extractors/neoextractors/neobaseextractor.py in __init__(self, stream_id, **neo_kwargs)
     24     def __init__(self, stream_id=None, **neo_kwargs):
     25 
---> 26         _NeoBaseExtractor.__init__(self, **neo_kwargs)
     27 
     28         # check channel

~/miniconda3/envs/py3/lib/python3.9/site-packages/spikeinterface/extractors/neoextractors/neobaseextractor.py in __init__(self, **neo_kwargs)
     14         neoIOclass = eval('neo.rawio.' + self.NeoRawIOClass)
     15         self.neo_reader = neoIOclass(**neo_kwargs)
---> 16         self.neo_reader.parse_header()
     17 
     18         assert self.neo_reader.block_count() == 1, \

~/miniconda3/envs/py3/lib/python3.9/site-packages/neo/rawio/baserawio.py in parse_header(self)
    183 
    184         """
--> 185         self._parse_header()
    186         self._check_stream_signal_channel_characteristics()
    187 

~/miniconda3/envs/py3/lib/python3.9/site-packages/neo/rawio/openephysrawio.py in _parse_header(self)
    174         # and create streams channels (keep natural order 'CH' first)
    175         stream_ids, order = np.unique(chan_stream_ids, return_index=True)
--> 176         stream_ids = stream_ids[order]
    177         signal_streams = [(f'Signals {stream_id}', f'{stream_id}') for stream_id in stream_ids]
    178         signal_streams = np.array(signal_streams, dtype=_signal_stream_dtype)

IndexError: index 70 is out of bounds for axis 0 with size 3
```

**Comment by samuelgarcia** [comment] 2022-02-09 07:38
Hi Chris,
Cool to see you here.
I really to fix this soon.
I am procrastinating a bit on that particular point. The todo list is so big!
I promise I will do it soon.

**Comment by alejoe91** [comment] 2022-02-09 08:29
> Hi Théo. i will have a look onthis super soon. I pomise.

Don't trust him @cxrodgers ahahah! Just kidding, should be a quick fix!

**Comment by cxrodgers** [comment] 2022-02-09 13:37
Ha I'm sure you have many things to work on! This is not so urgent, at least from my perspective.

**Comment by phanhuynh** [comment] 2022-03-07 14:35
Hello -- just wanted to add that our lab would also benefit greatly from this fix.  Thank you, @samuelgarcia !!!

**Comment by samuelgarcia** [comment] 2022-03-09 07:51
Same as https://github.com/NeuralEnsemble/python-neo/issues/1055

**Comment by samuelgarcia** [comment] 2022-03-09 11:38
Hi all.
Sorry for so long delay.
Could you test this PR 1095 in neo ?
https://github.com/NeuralEnsemble/python-neo/pull/1095

You will need to pull from my repo/branch [samuelgarcia:fix_openephys_legacy](https://github.com/samuelgarcia/python-neo/tree/fix_openephys_legacy)

**Comment by ToGauvrit** [comment] 2022-03-09 16:06
Hi Sam,
Thank you  the bug seems to be fixed with this PR!!

**Comment by samuelgarcia** [comment] 2022-03-09 16:25
Cool. Lets wait that a few others test it and we merge.

**Comment by JuliaSprenger** [comment] 2022-03-10 09:27
https://github.com/NeuralEnsemble/python-neo/pull/1095 has been merged.

**Closed** 2022-03-10 09:39 UTC
Labels: NEO

**Comment by phanhuynh** [comment] 2022-03-11 11:36
Hello @samuelgarcia , thank you for working on this!  
Unfortunately, even with neo==0.10.2, I'm still getting this error.
I'm using neuronexus probe through openephys.
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Input In [13], in <module>
      1 recording_folder = 'vinca_nn_data\VS15_2022-03-01_16-02-15'
----> 2 recording = se.neoextractors.openephys.OpenEphysLegacyRecordingExtractor(recording_folder, stream_id=None)

File ~\anaconda3\envs\siphy_env\lib\site-packages\spikeinterface\extractors\neoextractors\openephys.py:38, in OpenEphysLegacyRecordingExtractor.__init__(self, folder_path, stream_id)
     36 def __init__(self, folder_path, stream_id=None):
     37     neo_kwargs = {'dirname': folder_path}
---> 38     NeoBaseRecordingExtractor.__init__(self, stream_id=stream_id, **neo_kwargs)
     40     self._kwargs = dict(folder_path=str(folder_path), stream_id=stream_id)

File ~\anaconda3\envs\siphy_env\lib\site-packages\spikeinterface\extractors\neoextractors\neobaseextractor.py:26, in NeoBaseRecordingExtractor.__init__(self, stream_id, **neo_kwargs)
     24 def __init__(self, stream_id=None, **neo_kwargs):
---> 26     _NeoBaseExtractor.__init__(self, **neo_kwargs)
     28     # check channel
     29     # TODO propose a meachanisim to select the appropriate channel groups
     30     # in neo one channel group have the same dtype/sampling_rate/group_id
     31     # ~ channel_indexes_list = self.neo_reader.get_group_signal_channel_indexes()
     32     stream_channels = self.neo_reader.header['signal_streams']

File ~\anaconda3\envs\siphy_env\lib\site-packages\spikeinterface\extractors\neoextractors\neobaseextractor.py:16, in _NeoBaseExtractor.__init__(self, **neo_kwargs)
     14 neoIOclass = eval('neo.rawio.' + self.NeoRawIOClass)
     15 self.neo_reader = neoIOclass(**neo_kwargs)
---> 16 self.neo_reader.parse_header()
     18 assert self.neo_reader.block_count() == 1, \
     19     'This file is neo multi block spikeinterface support one block only dataset'

File ~\anaconda3\envs\siphy_env\lib\site-packages\neo\rawio\baserawio.py:185, in BaseRawIO.parse_header(self)
    172 def parse_header(self):
    173     """
    174     This must parse the file header to get all stuff for fast use later on.
    175 
   (...)
    183 
    184     """
--> 185     self._parse_header()
    186     self._check_stream_signal_channel_characteristics()

File ~\anaconda3\envs\siphy_env\lib\site-packages\neo\rawio\openephysrawio.py:176, in OpenEphysRawIO._parse_header(self)
    174 # and create streams channels (keep natural order 'CH' first)
    175 stream_ids, order = np.unique(chan_stream_ids, return_index=True)
--> 176 stream_ids = stream_ids[order]
    177 signal_streams = [(f'Signals {stream_id}', f'{stream_id}') for stream_id in stream_ids]
    178 signal_streams = np.array(signal_streams, dtype=_signal_stream_dtype)

IndexError: index 64 is out of bounds for axis 0 with size 2
```

**Comment by phanhuynh** [comment] 2022-03-15 09:52
Hello, perhaps this issue should be in another channel?  Or perhaps I should add more details?

**Comment by samuelgarcia** [comment] 2022-03-15 10:07
Hi @phanhuynh,
you need to install neo from source master branch.
In neo 0.10.2 was still there.

**Comment by phanhuynh** [comment] 2022-03-15 15:12
@samuelgarcia : it works!  thank you yet again!

**Comment by phanhuynh** [comment] 2022-06-24 12:17
Hello again, 
I'm trying to run this on a new computer and the problem came back, unfortunately.
Even with the latest version of neo:
`Finished processing dependencies for neo==0.11.0.dev0`
I'm getting the error:
`IndexError: index 64 is out of bounds for axis 0 with size 2`

Thoughts?

**Comment by samuelgarcia** [comment] 2022-06-24 16:08
Oh yes sorry. You are outside the conatiner.
This is something else.
You need to get latest python-code from master and install from code source.

**Comment by phanhuynh** [comment] 2022-06-28 12:23
Hi @samuelgarcia , thank you for your response.  
Just to be clear, I've already installed the latest version of Neo from the Git repository:
```
$ git clone git://github.com/NeuralEnsemble/python-neo.git
$ cd python-neo$ python setup.py install
```

This led to:
`Finished processing dependencies for neo==0.11.0.dev0`

Do you have a different/newer version somehow?

Thank you again,

**Comment by phanhuynh** [comment] 2022-07-01 15:03
Hello @samuelgarcia ! I reinstalled Anaconda and then reinstalled Neo and the problem is solved.  Bizarre.  Thank you!

**Comment by samuelgarcia** [comment] 2022-07-01 17:23
good to read that!

**Comment by eejd** [comment] 2022-10-24 16:59
Olá all,

I am also having trouble reading with the new Neo reader for the Legacy OpenEphys format. I don't know if anyone has this working, but my case is that the data is not loaded at all with a `index 0 is out of bounds for axis 0 with size 0` error. I have been reading through the code to try to find good points to debug the problem, but so far I don't have a good enough sense of the new Neo architecture to feel comfortable. What is the best approach to trying to identify the problem and help provide a fix? What I can say is the classic pyopenephys (CINPLA) loads the same directory and recordings.

**Comment by JuliaSprenger** [comment] 2022-10-25 10:03
Hi @eejd!
I am not sure what exactly causes the issue. Have you also tested this with the latest neo version (0.11.1)? If the issue persists, would it be possible for you to provide an example data session for debugging?

**Comment by eejd** [comment] 2022-10-28 16:00
I believe I found the problem. There was a ".spikes" file with 0 extent (only header) that was loaded and was in array position [0] in 'spike_data'. So, the code was failing here: `wf_gain = 1000. / data_spike[0]['gains'][0]` and it was because there was no data in `data_spike[0]`. There should be a test for this corner case. I'm now testing the rest of my code using the new Neo code base using the current git repo version.

**Comment by alejoe91** [comment] 2022-10-28 16:08
@eejd can you open an issue in Neo?
