### ISSUE TITLE
PCA not respecting `n_jobs` -- potential `ProcessPoolExecutor` issue

### ISSUE THREAD

**Issue by cheydrick** [SpikeInterface/spikeinterface#2817] opened 2024-05-07 15:10 UTC
The "Fitting PCA" step in the export to Phy process isn't respecting the n_jobs argument anymore.

I have set the global n_jobs parameter to 4 with:
si.set_global_job_kwargs(n_jobs=4)

When using SpikeInterface from April 17 (commit hash 33d478ab9) I can see that only four cores are being used while export_to_phy() is running.
![fittingpca_Apr17](https://github.com/SpikeInterface/spikeinterface/assets/1140582/e8584bf6-4e52-4e6f-9497-7b4163ede9d2)

However, when using SpikeInterface from May 6 (commit hash 42e1f024a) the "Fitting PCA" step is saturating all cores:
![fittingpca_may6](https://github.com/SpikeInterface/spikeinterface/assets/1140582/5f2d4091-6336-4207-93f8-5a2d115181a2)

Thanks,
Chris
chris@plexon.com

**Comment by zm711** [comment] 2024-05-07 18:25
Maybe related to #2696... 

Thanks for the report. I'll see if I can track this down.

**Comment by cheydrick** [comment] 2024-05-07 18:46
@zm711 it's an int.

si.set_global_job_kwargs(n_jobs=4)

**Comment by zm711** [comment] 2024-05-07 19:05
Could you do me a favor and run with `verbose=True` inside the export_to_phy. There has been some work on `verbose` so it might not work but it would be nice to see the max amount of information. Specifically to see how many jobs are being passed to the `ChunkRecordingExecutor`.

**Comment by zm711** [comment] 2024-05-07 19:06
The other thing we may need to look at is this line where we send the `sorting.to_multiprocessing`. It seems like `NumpySorting` would be converted to `SharedMem` here. Is that desired? 
https://github.com/SpikeInterface/spikeinterface/blob/42e1f024aaa0c2af823f715a78d1d95a33807732/src/spikeinterface/postprocessing/principal_component.py#L351-L360

https://github.com/SpikeInterface/spikeinterface/blob/42e1f024aaa0c2af823f715a78d1d95a33807732/src/spikeinterface/core/basesorting.py#L651-L681

**Comment by cheydrick** [comment] 2024-05-08 13:44
@zm711 Looks like verbose is True by default.

https://github.com/SpikeInterface/spikeinterface/blob/42e1f024aaa0c2af823f715a78d1d95a33807732/src/spikeinterface/exporters/to_phy.py#L37

I explicitly set it to True anyways, but the output was the same as in my screenshots above.

**Comment by zm711** [comment] 2024-05-08 13:52
Unfortunately (and this is why verbose needs to be fixed), is that that verbose is just for the function and not at a global level passed into the other functions that accept verbose. So that's why it doesn't do what I wanted. I'll try to dig a bit more by running the PCA by itself and see if I can see what is going on.

**Comment by zm711** [comment] 2024-05-08 19:12
I think we have to wait for @samuelgarcia to comment on this one. But based on my reading the n_jobs being fed into the `ProcessPoolExecutor` is just a max number of processes. So technically the OS can move those processes around however it wants (for example we could also set n_jobs > number of cores and it would just have to schedule those extra processes onto the processors). This doesn't explain why the switch occurred with changing to NumpySorting from SharedMemSorting, but n_jobs cannot absolutely be guaranteed to be equal to the cores since the OS has a say in this.

**Comment by alejoe91** [comment] 2024-07-02 12:50
Looking at this again, I have no clue why this is maxing out the CPUs as `n_jobs` seems to be correctly propagated to the `ProcessPoolExecutor` [here](https://github.com/SpikeInterface/spikeinterface/blob/main/src/spikeinterface/postprocessing/principal_component.py#L398)...

**Comment by zm711** [comment] 2024-07-02 12:52
I don't know why it would change with one of our commits, but n_jobs are just the number of processes not the number of cores so it could be a Windows update as well that changed how they were scheduling processes and so it was bouncing the processes to all the cores rather than limiting to specific cores. Seems inefficient, but not impossible right?

**Comment by cheydrick** [comment] 2024-07-02 17:52
@alejoe91 and @zm711 thanks for commenting on this - it made me take a look again, and I figured out the problem.

I decided to verify that commit 33d478a worked correctly with a fresh conda environment, and found that it also had the problem of saturating my processors.

Fortunately I had my old "good" conda environment from April 17 that didn't have this problem, and I compared the versions all of the installed packages between this "good" environment and the fresh environment. Long story short, changing scipy from version 1.13.1 to 1.12.0 fixed the problem. The "Fitting PCA" step no longer saturates my processor.

**Comment by zm711** [comment] 2024-07-02 17:56
Do you think we should add a note somewhere that scipy can saturate cores? So people don't blame us-- @alejoe91 ?

**Comment by alejoe91** [comment] 2024-07-02 17:56
@cheydrick Thanks for tracking this down!! Yeah let's keep this open so that we can investigate more

**Comment by samuelgarcia** [comment] 2024-07-03 07:09
My guess is the folowing:
n_jobs is the number of process and I guess this is correct.

In job_tools.py the number of thread per process is clip to 1 with max_threads_per_process and using the threadpoolctl package and so for save(n_jobs=4) you would not have the same. Is it right ?

But the pca fitting code (of Alessio) use ProcessPoolExecutor directly and is bypassing this max_threads_per_process and so scipy use as much as core as possible per process which is not efficient.

I guess that is this on the back of Alessio. Good luck camarade :)

**Comment by alejoe91** [comment] 2024-07-03 07:14
Good guess! So I should just add the max_threads_per_process

**Comment by zm711** [comment] 2024-07-19 21:41
I'm going to change the title of this issue to make clear that this is a ProcessPoolExcector issue in PCA.

**Comment by zm711** [comment] 2024-12-03 22:41
I think we should close this. The issue is in versions of scipy. We are working on trying to tweak our multiprocessing so maybe that will fix this in the future, but the solution would be to limit scipy if core number really needs to be respected.

**Closed by zm711** 2024-12-03 22:41 UTC
Labels: exporters, concurrency
