### ISSUE TITLE
Pandas import error while using the klusta docker image

### ISSUE THREAD

**Issue by guidomeijer** [SpikeInterface/spikeinterface#1565] opened 2023-04-20 13:02 UTC
Hi! I'm trying to spikesort some tetrode data with Klusta but when I run the spikesorting using Docker I'm getting an `ModuleNotFoundError: No module named 'pandas'` error. Looks like a pip install of pandas needs to be added to the docker image. I tried doing it myself but I'm not very familiar with Docker images yet.

**Comment by alejoe91** [comment] 2023-04-20 13:06
Hi @guidomeijer 

Can you paste the entire error? Also note that klusta is locked to python 3.7, while the latest SI requires 3.8 or higher. So to run klusta in docker, you'd need to install SI==0.96

**Comment by guidomeijer** [comment] 2023-04-20 13:24
I installed SI 0.96 in a fresh env and ran it again but still get the same. Here's the full error:
```
Starting container
Installing spikeinterface==0.96.0 in spikeinterface/klusta-base
Installing extra requirements: ['neo']
Running klusta sorter inside spikeinterface/klusta-base
Stopping container
Traceback (most recent call last):
  File "C:\Users\Neuropixel\Documents\PYTHON\pipeline_Neuropixel\run_spikesorting_tetrodes.py", line 30, in <module>
    sort = run_sorter('klusta',
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Neuropixel\mambaforge\envs\si96\Lib\site-packages\spikeinterface\sorters\runsorter.py", line 137, in run_sorter
    return run_sorter_container(
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Neuropixel\mambaforge\envs\si96\Lib\site-packages\spikeinterface\sorters\runsorter.py", line 578, in run_sorter_container
    raise SpikeSortingError(
spikeinterface.sorters.utils.misc.SpikeSortingError: Spike sorting in docker failed with the following error:
b'Traceback (most recent call last):\n  File "/Users/Neuropixel/Documents/Jasmin/ML8B1_P22_s1_2023-02-27_10-37-42_maze + sleep/Record Node 101/experiment1/recording1/in_container_sorter_script.py", line 4, in <module>\n    from spikeinterface.sorters import run_sorter_local\n  File "/usr/local/lib/python3.7/site-packages/spikeinterface/sorters/__init__.py", line 2, in <module>\n    from .sorterlist import *\n  File "/usr/local/lib/python3.7/site-packages/spikeinterface/sorters/sorterlist.py", line 1, in <module>\n    from .combinato import CombinatoSorter\n  File "/usr/local/lib/python3.7/site-packages/spikeinterface/sorters/combinato/__init__.py", line 1, in <module>\n    from .combinato import CombinatoSorter\n  File "/usr/local/lib/python3.7/site-packages/spikeinterface/sorters/combinato/combinato.py", line 10, in <module>\n    from spikeinterface.extractors import CombinatoSortingExtractor\n  File "/usr/local/lib/python3.7/site-packages/spikeinterface/extractors/__init__.py", line 4, in <module>\n    from .bids import read_bids_folder\n  File "/usr/local/lib/python3.7/site-packages/spikeinterface/extractors/bids.py", line 4, in <module>\n    import pandas as pd\nModuleNotFoundError: No module named \'pandas\'\n'
```

**Comment by alejoe91** [comment] 2023-04-20 13:28
Thanks! What type is the input recording? I'll try to reproduce it on my side

**Comment by alejoe91** [comment] 2023-04-20 14:57
A very simple workaround would be the following:

```
recoridng.extra_requirements.append('pandas')
```

The problem is on our side: the `read_bids` file imports pandas in an unprotected way, will fix it on main but I guess that my suggestion is the only back-compatible one.

BTW, have you tried mountainsort4 on tetrode data?

**Comment by guidomeijer** [comment] 2023-04-20 16:27
Thanks! I also had to do that for scikit-learn. But now I have a new error:
```
SpikeSortingError: Spike sorting in docker failed with the following error:
b'Versions are not the same. This might lead to errors. Use  spikeinterface version 0.97.1\nTraceback (most recent call last):\n  File "/Users/Neuropixel/Documents/Jasmin/ML8B1_P22_s1_2023-02-27_10-37-42_maze + sleep/Record Node 101/experiment1/recording1/in_container_sorter_script.py", line 9, in <module>\n    recording = load_extractor(\'/Users/Neuropixel/Documents/Jasmin/ML8B1_P22_s1_2023-02-27_10-37-42_maze + sleep/Record Node 101/experiment1/recording1/in_container_recording.json\')\n  File "/usr/local/lib/python3.7/site-packages/spikeinterface/core/base.py", line 821, in load_extractor\n    return BaseExtractor.load(file_or_folder_or_dict, base_folder=base_folder)\n  File "/usr/local/lib/python3.7/site-packages/spikeinterface/core/base.py", line 513, in load\n    extractor = BaseExtractor.from_dict(d, base_folder=base_folder)\n  File "/usr/local/lib/python3.7/site-packages/spikeinterface/core/base.py", line 340, in from_dict\n    extractor = _load_extractor_from_dict(d)\n  File "/usr/local/lib/python3.7/site-packages/spikeinterface/core/base.py", line 767, in _load_extractor_from_dict\n    extractor = cls(**kwargs)\nTypeError: __init__() got an unexpected keyword argument \'all_annotations\'\n'
```

I wanted to use Klusta because that's what the people who asked me to run this for them use. Mountainsort is running fine so maybe I can convince them to switch.

**Comment by guilhemibos** [comment] 2023-05-22 07:11
Hi

I have the exact same issue when I try to run Klusta however the above mentionned solution failed:

SpikeSortingError: Spike sorting in docker failed with the following error:
b'Traceback (most recent call last):\n  File "/openephys/2023-01-20_11-00-24/SpikeInterface/klusta/Dockers/in_container_sorter_script.py", line 4, in \n    from spikeinterface.sorters import run_sorter_local\n  File "/usr/local/lib/python3.7/site-packages/spikeinterface/sorters/__init__.py", line 2, in \n    from .sorterlist import *\n  File "/usr/local/lib/python3.7/site-packages/spikeinterface/sorters/sorterlist.py", line 1, in \n    from .combinato import CombinatoSorter\n  File "/usr/local/lib/python3.7/site-packages/spikeinterface/sorters/combinato/__init__.py", line 1, in \n    from .combinato import CombinatoSorter\n  File "/usr/local/lib/python3.7/site-packages/spikeinterface/sorters/combinato/combinato.py", line 10, in \n    from spikeinterface.extractors import CombinatoSortingExtractor\n  File "/usr/local/lib/python3.7/site-packages/spikeinterface/extractors/__init__.py", line 4, in \n    from .bids import read_bids_folder\n  File "/usr/local/lib/python3.7/site-packages/spikeinterface/extractors/bids.py", line 4, in \n    import pandas as pd\nModuleNotFoundError: No module named \'pandas\'\n'


recording.extra_requirements.append('pandas')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[15], line 1
----> 1 recording_areas.extra_requirements.append('pandas')

AttributeError: 'dict' object has no attribute 'extra_requirements'

Any ideas?
Thanks

**Comment by alejoe91** [comment] 2023-11-06 12:08
@guilhemibos were you able to fix this? Seems like `recording_areas` is not a `BaseRecording`.

Anyways, will close this for now, feel free to reopen or open another issue!

**Closed by alejoe91** 2023-11-06 12:08 UTC
Labels: container
