### ISSUE TITLE
`SortingAnalyzer` `.compute("spike_amplitudes")` error

### ISSUE THREAD

**Issue by JoeZiminski** [SpikeInterface/spikeinterface#2887] opened 2024-05-20 17:43 UTC
I'm running into trouble with the below code:

```
import spikeinterface as si

# Generate curated sorting
recording, sorting = si.generate_ground_truth_recording()  # num_channels=64

sorting_analyzer = si.create_sorting_analyzer(
    sorting, recording
)

sorting_analyzer.compute("random_spikes")
sorting_analyzer.compute("waveforms")
sorting_analyzer.compute("templates")

sorting_analyzer.compute(
    "spike_amplitudes",
    peak_sign="neg"  # "pos" does not work either"
)

# sorting_analyzer.compute("amplitude_scalings")
```

which gives an error:

```
Traceback (most recent call last):
  File "/Users/joeziminski/PycharmProjects/si-dev/main.py", line 14, in <module>
    sorting_analyzer.compute(
  File "/Users/joeziminski/git_repos/spikeinterface/src/spikeinterface/core/sortinganalyzer.py", line 869, in compute
    return self.compute_one_extension(extension_name=input, save=save, **kwargs)
  File "/Users/joeziminski/git_repos/spikeinterface/src/spikeinterface/core/sortinganalyzer.py", line 924, in compute_one_extension
    for child in _get_children_dependencies(extension_name):
  File "/Users/joeziminski/git_repos/spikeinterface/src/spikeinterface/core/sortinganalyzer.py", line 1217, in _get_children_dependencies
    children = _extension_children[extension_name]
KeyError: 'spike_amplitudes'
```

I'm following from [here](https://spikeinterface.readthedocs.io/en/latest/tutorials/waveform_extractor_to_sorting_analyzer.html), apologies if I have missed something!

**Comment by zm711** [comment] 2024-05-20 17:50
@JoeZiminski, could you try restarting your kernel. I'm not 100% certain this is the issue, but the way the extensions are generated can lead to an issue if you change code partway through analysis. Just curious is restarting with a clean kernel fixes this issue.

I just tested your code with a fresh ipython session and it worked fine.

**Comment by JoeZiminski** [comment] 2024-05-20 17:58
Thanks @zm711 I am also getting this in a fresh kernel / running as a script.  I am on macOS m2, I'll try and replicate on windows in a fresh environment, no idea if OS should matter but I can't think of anything else at this stage 🤔

**Comment by zm711** [comment] 2024-05-20 18:37
I figured it out @JoeZiminski :).

When I tested I did `import spikeinterface.full as si` instead of just importing core. You are not import the postprocessing package so it's not working. 

I thought we had a better error for this/automatic loading, which seems to not be working anymore.

could you try re-running with a full import? And if that works then I think we need to improve the error messaging.

**Comment by zm711** [comment] 2024-05-20 18:59
@alejoe91 and @samuelgarcia 

The issue is this:
https://github.com/SpikeInterface/spikeinterface/blob/024c24afaec2d0a0476017c77a75f7c8a1dcb4b3/src/spikeinterface/core/sortinganalyzer.py#L924-L928

We try to delete before we "get" which means that non-core extensions don't work and we get an unhelpful error message. I'll try to open a PR switching the order and seeing if breaks anything unexpected.

**Comment by JoeZiminski** [comment] 2024-05-20 19:02
Thanks @zm711! that did the trick. I had a look around the `sorting_analyzer.py` but couldn't figure it out thanks for tracking down the root cause. I say this with absolutely no understanding of the requirements of the class and nature of the problem, but is it possible to avoid the global variables used in `sorting_analyzer.py`? Not sure if it's the case here but they are often the cause of many bugs and makes it difficult to follow the logic of the code.

**Comment by zm711** [comment] 2024-05-20 19:06
That's why I tagged Sam and Alessio. That's above my paygrade :) 

I did a draft PR to try to fix it, but I'm waiting to see if there are unintended consequences of this. Basically an auto-load was added just for the extensions that gets triggered by get_extension but since we were trying to clean-up before we had the extension registered we were getting a key error. If you already import the packages then they are registered at import so this isn't a problem (and why we hadn't discovered it yet is my guess).

**Comment by JoeZiminski** [comment] 2024-05-20 19:28
That's brilliant, thanks for solving this so fast. Is it worth to include this MRE (or something similar) as a quick unit test in `test_sortinganalyzer`?

**Comment by zm711** [comment] 2024-05-20 19:30
Yeah it probably is worth adding, I'll have to look at the tests though. Because once we've imported it might be too late. I'll have to see what the file looks like. I know adding more to the test suite is a big push (and will be part of the hackathon) so hopefully you can help out with !

**Closed** 2024-05-21 07:45 UTC
Labels: bug
