### ISSUE TITLE
question about reading Neuropixels data

### ISSUE THREAD

**Issue by Zeinab-Mohammadi** [SpikeInterface/spikeinterface#1811] opened 2023-07-10 20:09 UTC
Hi
 I am trying to read [this data](http://data.cortexlab.net/singlePhase3/) (data file is [here](http://data.cortexlab.net/singlePhase3/data/)) using spikeinterface as I want to sort it with Mountainsort5.
I think I should use [this code](https://spikeinterface.readthedocs.io/en/latest/how_to/analyse_neuropixels.html), but can I know which file should I go with? I mean from [this data link](http://data.cortexlab.net/singlePhase3/data/), what file names should I substitute instead of 'Rec_1_10_11_2021_g0' and 'imec0.ap' in your code? Another thing is that it seems that the common average referencing applied to it, so it’s not the raw data! Then what change should I make in my code? Thanks!

Sorry, but I am also getting this error though I installed the full version of spikeinterface: 
`module 'spikeinterface' has no attribute 'get_neo_streams'`

**Comment by h-mayorquin** [comment] 2023-07-11 10:39
Hi, @Zeinab-Mohammadi 

There seems to be a problem with your link of your data. In fact, all of your links seem to be pointing to the wrong place. I wonder what happened.

As for your error, can you share the script that makes it fail?

It works on my computer and it works in the documentation which we run as code:

```

In [1]: import spikeinterface.full as si

In [2]: hasattr(si, "get_neo_streams")
Out[2]: True
``` 

So, we will need to take a look at the context to help you.

**Comment by Zeinab-Mohammadi** [comment] 2023-07-11 19:21
Hi @h-mayorquin 
Thanks and sorry about that, it should be fine now but lmk if it still has any problem. Also, I was doing import spikeinterface as si, so now that error is ok. 
As I mentioned this is a file after CAR, so I think I should go with the below code and I am getting this error:
![error](https://github.com/SpikeInterface/spikeinterface/assets/76111159/5ba22d30-19c7-47d0-a659-338df41b842e)

**Comment by Zeinab-Mohammadi** [comment] 2023-07-11 19:34
Btw, do you know about a public dataset (synthetic or experimental data, both with many channels (>100) ) that is read/processed by spikeinterface and preferably sorted by MountainSort? For example in your website link is the data in this path publicly available? `base_folder = Path('/mnt/data/sam/DataSpikeSorting/neuropixel_example/')

spikeglx_folder = base_folder / 'Rec_1_10_11_2021_g0'`

**Comment by Zeinab-Mohammadi** [comment] 2023-07-12 14:20
Hi @h-mayorquin 
Thanks, but I think this is not true and it results in error. The Hopkins_20160722_g0_t0.imec.ap_CAR.bin data is in Neuropixels_data folder, but it can't print out the stream_names for some reason.
<img width="1042" alt="error2" src="https://github.com/SpikeInterface/spikeinterface/assets/76111159/5cb2ccaa-33e5-47e0-929f-ca7c1a80e4b8">

Btw, I used get_noise_levels as based on [this code](https://spikeinterface.readthedocs.io/en/latest/how_to/analyse_neuropixels.html), this data is after **CAR** as I mentioned, and is after transferred to **.bin** file. you can see this in the mentioned site as **check noise level** after transferring the file to **binary format**.
All of these are in the link I put in my first comment and here. Thanks

**Comment by alejoe91** [comment] 2023-07-12 14:32
Ok, so if the folder doesn't preserve the original spikeglx folder, you need to load the bin directly with the `read_binary` function. You cannot pass the path to the file directly to the functions, since they require a recording object.

**Comment by Zeinab-Mohammadi** [comment] 2023-07-12 14:46
only the name of the function is [here](https://spikeinterface.readthedocs.io/en/latest/modules/extractors.html), but is there an example somewhere?

**Comment by alejoe91** [comment] 2023-07-12 14:48
I just realized it's not in the API page, we'll add it! In the meanwhile you can find all arguments here: https://github.com/SpikeInterface/spikeinterface/blob/main/src/spikeinterface/core/binaryrecordingextractor.py#L13

**Comment by Zeinab-Mohammadi** [comment] 2023-07-12 14:53
As there is no example, it's better if you can write the code to use it with my file. Thanks
i.e. how should I import and use it?

**Comment by alejoe91** [comment] 2023-07-12 15:42
Sure, but I also recommend try to read the "docstrings" that I shared because it's a useful skill to be able to use them!

```
recording = si.read_binary("path-to-file.bin", num_channels=385, dtype="int16", sampling_frequency=30000, gain_to_uV=2.34)
recording = recording.remove_channels([recording.channel_ids[-1]])
```

A couple of notes: 

- the recording you are loading has an extra "SYNC" channel, so the number of channels need to be set 385. So we need to remove the extra channel (`remove_channels`)
- the file is loaded in `int16` type. The `gain_to_uV` allows you to convert to uV (1 sample = 2.34 uV)
- this will not load the geometry of the probe. You can add probe info as follows:
```
import numpy as np
locations = np.load("path-to-/channel_positions.npy")
recording.set_channel_locations(locations)
```

**Comment by Zeinab-Mohammadi** [comment] 2023-07-12 16:07
Great, thanks, but I am getting this error:
<img width="1086" alt="error4" src="https://github.com/SpikeInterface/spikeinterface/assets/76111159/43e45430-22e9-47d5-bb9d-48ae6e21207b">

**Comment by alejoe91** [comment] 2023-07-12 17:03
Mmm I guess locations are saved by kilosort and not for all channels. Can you try `print(locations.shape)`?

then you would need to manually create a NP1 layout and set the locations (or try to find another dataset!)

There are a bunch of dataset with Neurpopixels on DANDI: https://dandiarchive.org/

You can download the nwb file and then do:
```
import spikeinterface.extractors as se

recording = se.read_nwb_recording("path-to-file.nwb")
```

**Comment by Zeinab-Mohammadi** [comment] 2023-07-12 17:55
It is (374, 2). I think they excluded the Can you please explain more about how to make that NP1 please?
Also, I can see that [here](http://data.cortexlab.net/singlePhase3/), they have this code if it is useful :
`>> fn = 'rawDataSample.bin'; 
>> fid = fopen(fn, 'r'); 
>> dat = fread(fid, [385 Inf], '*int16'); 
>> fclose(fid); 
>> chanMap = readNPY('channel_map.npy'); 
>> dat = dat(chanMap+1,:); 
>> figure; imagesc(dat(:,1:30000))`

If I can not make it, I will try another dataset.

**Comment by Zeinab-Mohammadi** [comment] 2023-07-12 17:58
one more question, previously, I made had this code in Matlab to get a shorter data in .npy format corresponding to true channels:
`fid = fopen(fn, 'r'); 
dat = fread(fid, [385 Inf], '*int16'); 
fclose(fid); 
chanMap = readNPY('/.../channel_map.npy');
T = 11300000; %interested length, about 1/10 of data
dat2 = dat(chanMap+1,1:T); 
writeNPY(dat2, 'data_short.npy')`

**Comment by Zeinab-Mohammadi** [comment] 2023-07-12 19:13
I tried to sort the data with Mountainsortin in the below file. Can you please lmk if using Mountainsort with data from spikeinterface is correct here? Is there any issue? Thanks

`"Remember to active the enviroment as below "
# module load anaconda3/2023.3
# conda activate mountainsort

file ='/.../Neuropixels_data/'

import spikeinterface.full as si
import spikeinterface.preprocessing as spre
import mountainsort5 as ms5
import spikeinterface.extractors as se
import numpy as np
import spikeinterface.widgets as sw
import matplotlib.pyplot as plt
from pathlib import Path

recording = si.read_binary(file + 'Hopkins_20160722_g0_t0.imec.ap_CAR.bin', num_channels=385, dtype="int16", sampling_frequency=30000, gain_to_uV=2.34)
recording = recording.remove_channels([recording.channel_ids[-1]])
recording

locations = np.load(file + '/channel_positions.npy')
print(locations.shape)
recording.set_channel_locations(locations)

# noise_levels_microV = si.get_noise_levels(recording, return_scaled=True)
noise_levels_int16 = si.get_noise_levels(recording, return_scaled=False)

fig, ax = plt.subplots()
_ = ax.hist(noise_levels_int16, bins=np.arange(5, 30, 2.5))
ax.set_xlabel('noise')

# here we use static plot using matplotlib backend
# fig, axs = plt.subplots(ncols=1, figsize=(20, 10))

si.plot_timeseries(recording, backend='matplotlib',  clim=(-50, 50))


# plot some channels
fig, ax = plt.subplots(figsize=(20, 10))
some_chans = recording.channel_ids[[100, 150, 200, ]]
si.plot_timeseries({'data':recording}, backend='matplotlib', mode='line', ax=ax, channel_ids=some_chans)

# Make sure the recording is preprocessed appropriately
# lazy preprocessing
recording_filtered = spre.bandpass_filter(recording, freq_min=300, freq_max=6000)
recording_preprocessed: si.BaseRecording = spre.whiten(recording_filtered, dtype='float32')

# use scheme 1
sorting = ms5.sorting_scheme1(
    recording=recording_preprocessed,
    sorting_parameters=ms5.Scheme1SortingParameters(...)
)

# or use scheme 2
sorting = ms5.sorting_scheme2(
    recording=recording_preprocessed,
    sorting_parameters=ms5.Scheme2SortingParameters(...)
)

# or use scheme 3
sorting = ms5.sorting_scheme3(
    recording=recording_preprocessed,
    sorting_parameters=ms5.Scheme3SortingParameters(...)
)

# Now you have a sorting object that you can save to disk or use for further analysis

`

**Comment by alejoe91** [comment] 2023-07-13 07:36
Clearly the problem is that you don't have channel locations!

To replicate exactly the piece of Matlab code in SI you can do:
```
import spikeinterface as si
import numpy as np

recording = si.read_binary("path-to-file.bin", num_channels=385, dtype="int16", sampling_frequency=30000, gain_to_uV=2.34)
print(recording)

# this selects the "active" channels
channel_map = np.load("path-to/channel_map.npy")
recording = recording.channel_slice(recording.channel_ids[channel_map])
print(recording)

# load and set locations (now it should work)
locations = np.load("path-to-/channel_positions.npy")
recording.set_channel_locations(locations)
```


As for running spikeinterface (or any other sorter), you can use the `run_sorter()` function:
```
import spikeinterface.sorters as ss

sorting_ms5 = ss.run_sorter("mountainsort5", recording)
```

I recommend spending some time reading in detail the ["How to - get started"](https://spikeinterface.readthedocs.io/en/latest/how_to/get_started.html) and watching this introductory [video tutorial](https://drive.google.com/file/d/1-eiXo6aCPyaBa_uP9ldOCkUa4cZOB3vr/view?usp=share_link):

**Comment by Zeinab-Mohammadi** [comment] 2023-07-13 20:51
Great, thanks for the help and sending the links. I will look at them and ask questions if needed.

**Comment by alejoe91** [comment] 2023-07-14 07:27
Can you make sure you have the latest spikeinterface version? `pip install -U spikeinterface`

**Comment by Zeinab-Mohammadi** [comment] 2023-07-14 16:37
I did update but no difference. It is ok for **recording1** but not for **recording**, so, whatever happens, is with **recording**. Please see:
<img width="555" alt="error 9" src="https://github.com/SpikeInterface/spikeinterface/assets/76111159/c26a32ac-3029-471f-84de-4da023c77809">

**Comment by Zeinab-Mohammadi** [comment] 2023-07-14 16:37
Also,  If I want to sort/read half of the data (or generally only T recording samples), how should I do that, please?

**Comment by alejoe91** [comment] 2023-07-14 16:47
Then it's probably a bug. @Zeinab-Mohammadi I recommend reading the documentation thoroughly ;)

Especially this part: https://spikeinterface.readthedocs.io/en/latest/modules/index.html

I'll close the issue because it's too general. Feel free to open another one for the plotting bug and one for each specific question you have. You can also search in the Issue page for some keywords to see if some similar issues were solved.

**Closed by alejoe91** 2023-07-14 16:47 UTC
Labels: question, extractors

**Comment by Zeinab-Mohammadi** [comment] 2023-07-14 16:49
ok, thank you!
