### ISSUE TITLE
Concatenating files to sort together

### ISSUE THREAD

**Issue by vatsunlab** [SpikeInterface/spikeinterface#2201] opened 2023-11-14 13:36 UTC
Hello! I have multiple ~3 minute long recordings that I want to sort together. But when I try this:
![image](https://github.com/SpikeInterface/spikeinterface/assets/70519326/e299f87d-3a4a-401f-8f92-4b650b92a59b)

I get this runtime warning, and the size of the concatenated file is less than the size of any of the individual files:
![image](https://github.com/SpikeInterface/spikeinterface/assets/70519326/1479b2c8-8c88-4558-a2ee-e7d5c58bfd18)

Could you please let me know what I'm doing wrong? Greatly appreciate any help, thanks!

**Comment by alejoe91** [comment] 2023-11-14 13:40
Hi! Everything looks good and I think that the problem is in the overflow error (so it only affects the print statement). The number of samples and duration looks correct.

**Comment by vatsunlab** [comment] 2023-11-14 14:59
THanks. Continuing on, if I do:
![image](https://github.com/SpikeInterface/spikeinterface/assets/70519326/00384781-51a8-4f39-a46e-7f424d5e5b26)

I get this error:
![image](https://github.com/SpikeInterface/spikeinterface/assets/70519326/b032109e-96d0-4d4a-a4f6-bbfeaf920235)

Could you identify the problem? Thanks.

**Comment by alejoe91** [comment] 2023-11-14 15:01
@samuelgarcia @h-mayorquin could you take a look at this? Seems related to the pre-allocation of the memmap objects

**Comment by vatsunlab** [comment] 2023-11-14 15:25
Sure, the files are here: https://pitt-my.sharepoint.com/:f:/g/personal/vatsun_pitt_edu/ElNgdDIZN_1DvWj8FNpoEWQBdchbvEiQlPZLTaTm23q31w?e=9LgUyU
I will delete them after you grab it. Thank you!

**Comment by h-mayorquin** [comment] 2023-11-14 15:48
OK, I started downloading them. I will let you know when I am done. 

Can you share the complete script that you ran for the error? That is, I will need a `script.py` file that gets you the error above.

**Comment by vatsunlab** [comment] 2023-11-14 15:51
Hi, the script is in that folder too.

**Comment by alejoe91** [comment] 2023-11-14 17:53
It should!

**Comment by h-mayorquin** [comment] 2023-11-17 16:38
@vatsunlab the branch in https://github.com/SpikeInterface/spikeinterface/pull/2223 should solve your error. Could you test it?

**Comment by lakritzthemarmoset** [comment] 2023-11-21 20:35
> @vatsunlab the branch in #2223 should solve your error. Could you test it?

Hello! I am working in vatsunlab and attempted to implement the fix. It seemed to run the concatenation and writing of the binary recording but then this error happened: 

![error_1](https://github.com/SpikeInterface/spikeinterface/assets/151557813/7af3963c-6c09-4636-a57b-dcd1d323d6f5)

Not sure how to handle this. 

Thank you very much for the help!

**Comment by h-mayorquin** [comment] 2023-11-22 06:52
Hi, @lakritzthemarmoset .

Glad that the other problem was fixed.
Can you open a new issue and share with us the full script that produces the error?

You seem to be using docker in windows and trying to save your results in a mounted path (I see C: and D:) which is not supported yet. But share your script in a new issue and we will be able to help. Also, this is the same data you shared with use right?

I am closing this as the original issue was addressed.

**Closed by h-mayorquin** 2023-11-22 06:52 UTC
Labels: bug, core

**Comment by lakritzthemarmoset** [comment] 2023-11-22 21:46
> Hi, @lakritzthemarmoset .
> 
> Glad that the other problem was fixed. Can you open a new issue and share with us the full script that produces the error?
> 
> You seem to be using docker in windows and trying to save your results in a mounted path (I see C: and D:) which is not supported yet. But share your script in a new issue and we will be able to help. Also, this is the same data you shared with use right?
> 
> I am closing this as the original issue was addressed.

Hi @h-mayorquin, 

Thank you again for the help with the concatenation, I really appreciate it!

The docker problem was a simple fix of needing to open the Docker Desktop, which I had seen others online had the same problem in different scenarios (not with SpikeInterface). After that, everything ran smoothly. Do you still think a new issue needs to be opened? If so, I can get the full script after the holidays.

**Comment by h-mayorquin** [comment] 2023-11-23 04:26
Not at all. Happy to hear it was something simple to solve! 

Happy holidays and happy analysis!
